### ISSUE TITLE
Filtrer les citation par auteur

### ISSUE THREAD

**Issue by ZirconiumZr40** [MPSI1Thuillier/IPT#1]
Je propose d'intégrer à la commande .citation un filtre par rapport aux auteurs :
Celui permettrait d'avoir des citations d'un seul auteur (par exemple avec un ".citation VVK" on obtient obligatoirement une citation de VVK).

**Comment by ZirconiumZr40** [comment]
> 
> 
> Je propose d'intégrer à la commande .citation un filtre par rapport aux auteurs :
> Celui permettrait d'avoir des citations d'un seul auteur (par exemple avec un ".citation VVK" on obtient obligatoirement une citation de VVK).

**Comment by NathanFallet** [comment]
Mauvais repo, essaye [ici](https://github.com/MPSI1Thuillier/Bot)
